# Uncomment the next line to define a global platform for your project
# platform :ios, '10.3'

target 'weather_app' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for weather_app
  pod 'Alamofire', '~> 5.2'
  pod 'RxSwift', '~> 5'
  pod 'Swinject'

end
